config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  get '/help',  to: 'pages#help'
  get '/about', to: 'pages#about'
  get '/order', to: 'pages#order'

  resources :restaurants do
    resources :food_items
  end
  resources :food_orders do
    member do
      get :summary
    end
  end
  resources :order_items
  root to: 'pages#home'
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  attribute :price, :money
  VALID_PRICE_REGEX = /\A[0-9]*\.?[0-9]+\z/
  validates :name, presence: true, length: { maximum: 50 }
  validates :price, presence: true,
                    format: { with: VALID_PRICE_REGEX },
                    numericality: { only_integer: true }
  validates :category, presence: true
  belongs_to :restaurant
  has_many :order_items, dependent: :destroy
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :load_restaurant, :authenticate_user!

  def new
    @food_item = @restaurant.food_items.build
  end

  def create
    @food_item = @restaurant.food_items.build(food_params)
    if @food_item.save
      redirect_to @restaurant
    else
      flash.now[:danger] = 'Failed to save item.'
      render 'new'
    end
  end

  def edit
    @food_item = FoodItem.find(params[:id])
  end

  def update
    @food_item = FoodItem.find(params[:id])
    if @food_item.update_attributes(food_params)
      flash[:success] = 'Food item updated.'
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    FoodItem.find(params[:id]).destroy
    flash[:success] = 'Food item deleted'
    respond_to do |format|
      format.html { redirect_to @restaurant }
      format.js do
        flash.now[:success] = 'Food item deleted'
        @food = @restaurant.food_items.where(category: 'food')
        @drinks = @restaurant.food_items.where(category: 'drinks')
        @desserts = @restaurant.food_items.where(category: 'desserts')
        @editable = true
      end
    end
  end

  private

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def food_params
    params.require(:food_item).permit(:name, :price, :category)
  end
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/views/food_items/_food_item.html.erb
<div class="card food-card mx-3">
  <div class="card-body">
    <h5 class="card-title mb-2 font-weight-light">
      <%= food_item.name %>
    </h5>
    <h6 class="card-subtitle mb-2">
      <%= number_to_currency(food_item.price, unit: '₱') %>
    </h6>
  </div>
  <div class="card-footer">
    <% if @editable %>
      <%= link_to  image_tag('svg/pencil.svg', alt: 'edit icon',
      class: 'icon'), edit_restaurant_food_item_path(@restaurant, food_item),
                             class: 'btn' %>
      <%= link_to  image_tag('svg/trash.svg', alt: 'delete icon',
      class: 'icon'), restaurant_food_item_path(@restaurant, food_item), 
                             method: :delete,
                             remote: true,
                             data: { confirm: 'You sure?' },
                             class: 'ml-2 btn' %>
    <% else %>
      <%= form_for(:order_items, url: order_items_path(id: @food_order.id)) do |f| %>
        <!-- pass the food item to the next page  -->
        <%= hidden_field_tag :food_item_id, food_item.id %>
        <div class="form-group mb-2">
          <%= f.label :quantity %>
          <div class="input-group input-group-sm">
            <div class="input-group-addon">
              <span class="input-group-text"> x </span>
            </div>
            <%= f.number_field :quantity, value: 1, min: 1, class: 'form-control' %>
          </div>
        </div>
        <%= f.submit "Add", class: 'btn btn-outline-success' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/food_items/_food_item_form.html.erb
<%= form_for(@food_item, url: url, 
                         html: { class: 'col-md-4 mx-auto mb-5' } ) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.select(:category, options_for_select([['Food', "food"],
                                                ['Drinks', "drinks"],
                                                ['Desserts', "desserts"]],
                                                f.object.category),
                                                class: 'form-control') %>
  </div>

  <%= f.submit "Submit", class: 'btn btn-primary' %>
  <%= link_to  'Back', restaurant_path(@restaurant), class: 'btn btn-link ml-1' %>
<% end %>

app/views/food_items/destroy.js.erb
$("#flash").html("<%= j render 'shared/flash' %>")
$("#food-item").html("<%= j @food.empty? ? ('No food available') : (render @food) %>")
$("#drinks-item").html("<%= j @drinks.empty? ? ('No drinks available.') : (render @drinks) %>")
$("#desserts-item").html("<%= j @desserts.empty? ? ('No desserts available.') : (render @desserts) %>")

app/views/food_items/edit.html.erb
<%= provide(:title, 'Edit menu') %>
<h1 class="display-4 text-center pt-3">Edit food item</h1>

<%= render partial: 'food_item_form', locals: { 
               url: restaurant_food_item_path(@restaurant, @food_item) } %>

app/views/food_items/new.html.erb
<div class="text-center pt-4">
  <h1 class="display-4"><%= @restaurant.name %></h1>
  <p class="lead">Add a new menu item</p>
</div>

<%= render partial: 'food_item_form', locals: { url: restaurant_food_items_path } %>
 