config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  get '/help',  to: 'pages#help'
  get '/about', to: 'pages#about'
  get '/order', to: 'pages#order'

  resources :restaurants do
    resources :food_items
  end
  resources :food_orders do
    member do
      get :summary
    end
  end
  resources :order_items
  root to: 'pages#home'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true,
                   length: { maximum: 50 },
                   uniqueness: { case_sensitive: false }
  validates :contact, presence: true
  default_scope -> { order(name: :asc) }
  has_many :food_items, dependent: :destroy
  has_many :food_orders, dependent: :destroy
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!

  def show
    @restaurant = Restaurant.find(params[:id])
    @editable = true
    @food = @restaurant.food_items.where(category: 'food')
    @drinks = @restaurant.food_items.where(category: 'drinks')
    @desserts = @restaurant.food_items.where(category: 'desserts')
  end

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:success] = 'New restaurant added'
      redirect_to restaurants_url
    else
      render 'new'
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(restaurant_params)
      flash[:success] = 'Restaurant updated'
      redirect_to restaurants_url
    else
      render 'edit'
    end
  end

  def destroy
    @restaurants = Restaurant.all
    Restaurant.find(params[:id]).destroy
    flash[:success] = 'Restaurant deleted'
    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.js { flash.now[:success] = 'Restaurant deleted' }
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :contact)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form_for_restaurants.html.erb
<%= form_for(@restaurant, html: { class: "col-md-4 mx-auto mb-5" }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", autofocus: true %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :contact %>
    <%= f.text_field :contact, class: "form-control" %>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  
  <%= link_to  'Back', restaurants_url, class: "ml-2" %>
<% end %>

app/views/restaurants/_restaurant.html.erb
<li class="list-group-item d-flex justify-content-between align-items-center">
  <%= link_to restaurant.name, restaurant %>
  <div>
    <%= link_to image_tag('svg/pencil.svg', alt: 'edit icon',
    class: 'icon'), edit_restaurant_path(restaurant), class: "btn btn-primary" %> 
    <%= link_to image_tag('svg/trash.svg', alt: 'delete icon',
    class: 'icon'), restaurant, method: :delete,
                                remote: true,
                                data: { confirm: "You sure?" },
                                class: "btn btn-danger" %>
  </div>
</li>

app/views/restaurants/destroy.js.erb
$("#flash").html("<%= j render 'shared/flash' %>")
$("#restaurants_list").html("<%= j render @restaurants %>")

app/views/restaurants/edit.html.erb
<div class="text-center pt-4">
  <h1 class="display-4">Edit Restaurant</h1>
  <p class="lead"><%= @restaurant.name %></p>
</div>
<%= render 'form_for_restaurants' %>

app/views/restaurants/index.html.erb
<% provide(:title, 'Restaurants') %>
<div class="text-center my-4">
  <h1 class="display-4">Restaurants</h1>
  <%= link_to  'Add new restaurant', new_restaurant_path, 
                                     class: "btn btn-primary btn-warning" %>

</div>
<ul class="list-group list-unstyled col-md-4 mx-auto mb-5" id="restaurants_list">
  <%= render @restaurants %>
</ul>

app/views/restaurants/new.html.erb
<h1 class="display-4 text-center">Create Restaurant</h1>
<p class="lead text-center">Add a new restaurant.</p>
<%= render 'form_for_restaurants' %>

app/views/restaurants/show.html.erb
<%= provide(:title, 'Restaurant') %>
<div class="restaurant-header mx-2 mb-3 p-3">
  <h1 class="display-4"><%= @restaurant.name %></h1>
  <p class="lead mb-0">
    <%= image_tag  'svg/map-marker.svg', alt: 'address icon',
                                   class: 'icon food-item-icon' %>
    <%= @restaurant.address %>
  </p>
  <p class="lead mb-0">
    <%= image_tag  'svg/phone.svg', alt: 'phone icon',
                                   class: 'icon food-item-icon' %>
    <%= @restaurant.contact %>
  </p>
  <%= link_to  'Back', restaurants_url, class: 'btn btn-link' %>
</div>

<div class="text-left pl-4">
  <h2 class="font-weight-light d-none d-md-block">Menu</h2>
  <h4 class="d-block d-md-none">Menu</h4>
  <%= link_to image_tag('svg/plus.svg', alt: 'plus icon',
  class: 'icon') + " Add menu items", new_restaurant_food_item_path(@restaurant),
                                        class: "btn btn-outline-dark" %>
</div>

<section class="menu">
  <%= render 'shared/menu' %>
</section>