config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  get '/help',  to: 'pages#help'
  get '/about', to: 'pages#about'
  get '/order', to: 'pages#order'

  resources :restaurants do
    resources :food_items
  end
  resources :food_orders do
    member do
      get :summary
    end
  end
  resources :order_items
  root to: 'pages#home'
end

app/views/layouts/_footer.html.erb
  <footer class="bg-light justify-content-center">
    <small> Built by Arvy Petil &copy; 2018</small>
  </footer>

app/views/layouts/_header.html.erb
<nav class="navbar fixed-top navbar-expand-md bg-light navbar-light justify-content-end">
  <div class="container-fluid justify-content-end">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbar">
      <ul class="navbar-nav text-center">
        <li class="nav-item"><%= link_to  'Home', root_url, class: "nav-link" %></li>
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to  'Orders', new_food_order_path, class: "nav-link" %></li>
        <% end %>
        <li class="nav-item"><%= link_to  'Restaurants', restaurants_path, class: "nav-link" %></li>
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to  'Sign out', destroy_user_session_path,
                                                      method: :delete, class: "nav-link" %></li>
        <% else %>
          <li class="nav-item"><%= link_to  'Sign in', new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid mb-0" id="body">
      <%= render 'layouts/header' %>
      <div id="flash">
        <%= render 'shared/flash' %>
      </div>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>